### ISSUE TITLE
想問一下變形校正問題

### ISSUE THREAD

**Issue by thi23459112** [dadadadawjb/CLPDetector#1]
你好
能否單純做一個變形校正的代碼
我已經有一大堆用yolo裁切車牌的小圖片
車牌顏色有白底 紅底 綠底跟黃底

但因為傾斜車牌 很難校正 不知道你那邊方不方便釋出旋轉及校正的代碼
謝謝

**Comment by dadadadawjb** [comment]
> 你好 能否單純做一個變形校正的代碼 我已經有一大堆用yolo裁切車牌的小圖片 車牌顏色有白底 紅底 綠底跟黃底
> 
> 但因為傾斜車牌 很難校正 不知道你那邊方不方便釋出旋轉及校正的代碼 謝謝

Hi, 

thanks for your attention. For the rectification, this project adopts two different methods, named "**Shape-based Rectification**" and "**Color-based Rectification**".

The corresponding codes are the functions [ChineseLicensePlateDetector.shape_rectification](https://github.com/dadadadawjb/CLPDetector/blob/5664fc0743224d3e2604c8788542a81aae941aab/detector.py#L291) and [ChineseLicensePlateDetector.color_rectification](https://github.com/dadadadawjb/CLPDetector/blob/5664fc0743224d3e2604c8788542a81aae941aab/detector.py#L606). You can see the pipeline diagrams in [README/structures](https://github.com/dadadadawjb/CLPDetector#structures) to understand their operations. Roughly speaking, they both receive the RoI which is the "small cut" of the region of the plate, and then calculate 4 corner points of the slanted plate to calculate the perspective transformation matrix, and then apply to the RoI to output the rectified small image. And these operations depend on some pre-defined hyper-parameters, which can be found in [config](https://github.com/dadadadawjb/CLPDetector/blob/main/config.py) and may need tuning to specific data.

Hope that helps!
